### ISSUE TITLE
遇到几个问题

### ISSUE THREAD

**Issue by DrunkenMouse** [castial/HYFileManager#2]
+ (BOOL)createFileAtPath:(NSString *)path content:(NSObject *)content overwrite:(BOOL)overwrite 内部因为error没有设置，所以会不会导致重复调用?

+(NSNumber *)sizeOfDirectoryAtPath:(NSString *)path error:(NSError *__autoreleasing *)error 
为何获取文件夹大小时，要先获取文件夹的目录大小而后深遍历文件夹后累加所有目录和文件大小？

+(NSString *)sizeFormattedOfFileAtPath:(NSString *)path error:(NSError *__autoreleasing *)error 
获取文件大小，返回格式化后的数值。 内部if(!size) 判断条件为如果size不存在就格式化处理，存在就返回nil 是不是反了？

+(BOOL)isNotError:(NSError **)error是为了转换错误信息,如果错误信息为空则返回YES。但好像没用到吧？

单独下载打开后因为没有导入UIKit框架导致没有查找到[UIImage class]而报错

**Comment by castial** [comment]
谢谢反馈，已修复！

**Comment by HZRZCW** [comment]
下载下来的还是没有修复到的啊。。。
